Traceback (most recent call last):
  File "/homes/ogkourlias/Documents/BDC/Assignment6/assignment6.py", line 509, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/homes/ogkourlias/Documents/BDC/Assignment6/assignment6.py", line 503, in main
    process_file(args.chr, args.file, args.reference, headers, args.output, args.chunk)
  File "/homes/ogkourlias/Documents/BDC/Assignment6/assignment6.py", line 176, in process_file
    with open(output, "w") as fo:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'output/data/subset2/chr21.vcf.csv'
Traceback (most recent call last):
  File "/homes/ogkourlias/Documents/BDC/Assignment6/assignment6.py", line 509, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/homes/ogkourlias/Documents/BDC/Assignment6/assignment6.py", line 503, in main
    process_file(args.chr, args.file, args.reference, headers, args.output, args.chunk)
  File "/homes/ogkourlias/Documents/BDC/Assignment6/assignment6.py", line 176, in process_file
    with open(output, "w") as fo:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'output/data/subset1/chr21.vcf.csv'
